name: Portfolio Deployment

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main  # Specify the branch to check out

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16  # Use Node.js version 16

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Print AWS CLI Configuration
        run: aws configure list

      - name: Deploy static site to S3 bucket
        run: aws s3 sync . s3://aryanportfolio --delete
